# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Airbridge < Formula
  desc "AirBridge is a secure file transfer tool that uses RSA encryption."
  homepage "https://github.com/batuhan0sanli/airbridge"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/batuhan0sanli/AirBridge/releases/download/v0.1.3/airbridge_Darwin_x86_64.tar.gz"
      sha256 "65069033e04c4d5c587d4dddd70c6d3787014d5070b4ecbae075292ef0cebfba"

      def install
        bin.install "airbridge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/batuhan0sanli/AirBridge/releases/download/v0.1.3/airbridge_Darwin_arm64.tar.gz"
      sha256 "1c884879f91c5b2d929bc602989a43a36e60e27ab1e982f2b163fd4c4f047bfb"

      def install
        bin.install "airbridge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/batuhan0sanli/AirBridge/releases/download/v0.1.3/airbridge_Linux_x86_64.tar.gz"
      sha256 "c835f08a2012c218de9ab7f78848d7cce3e3f542ae3df869e6ea4629534e520a"
      def install
        bin.install "airbridge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/batuhan0sanli/AirBridge/releases/download/v0.1.3/airbridge_Linux_arm64.tar.gz"
      sha256 "45f3c28263d08d4e3876f29a13d17bd64cd00a9729452609eb4a33f5f55f6a34"
      def install
        bin.install "airbridge"
      end
    end
  end
end
