# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Airbridge < Formula
  desc "AirBridge is a secure file transfer tool that uses RSA encryption."
  homepage "https://github.com/batuhan0sanli/airbridge"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/batuhan0sanli/AirBridge/releases/download/v0.1.2/airbridge_Darwin_x86_64.tar.gz"
      sha256 "303bc91f5ff6f8367393499219a01b723feef1e4a5278ef08c9787445b05331e"

      def install
        bin.install "airbridge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/batuhan0sanli/AirBridge/releases/download/v0.1.2/airbridge_Darwin_arm64.tar.gz"
      sha256 "ecd4052111d6b6b27011b85bd48f30a4111c6a0f88ec43098f5f6838e28bddb5"

      def install
        bin.install "airbridge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/batuhan0sanli/AirBridge/releases/download/v0.1.2/airbridge_Linux_x86_64.tar.gz"
      sha256 "31be3b45b54ce594627e44887f0e87cd42f012c98e5938f45ad8b3d06acaf2bd"
      def install
        bin.install "airbridge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/batuhan0sanli/AirBridge/releases/download/v0.1.2/airbridge_Linux_arm64.tar.gz"
      sha256 "82095165c3d61df91fcc89e6fbd56c43f4f30f7d7fc0d881a6a38dd95423760d"
      def install
        bin.install "airbridge"
      end
    end
  end
end
