# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tai < Formula
  desc "Terminal AI — turn natural-language requests into shell commands using Claude."
  homepage "https://github.com/batuhan0sanli/tai"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/batuhan0sanli/tai/releases/download/v0.1.0/tai_Darwin_x86_64.tar.gz"
      sha256 "37cf712c465730a86ac247c1bb60e7876de79c8ad246d737f282e22ac37c5549"

      define_method(:install) do
        bin.install "tai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/batuhan0sanli/tai/releases/download/v0.1.0/tai_Darwin_arm64.tar.gz"
      sha256 "81e121e61c904ecb3c4d29529781b4dc65f4409eb7f620f4f8d0d49660110bee"

      define_method(:install) do
        bin.install "tai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/batuhan0sanli/tai/releases/download/v0.1.0/tai_Linux_x86_64.tar.gz"
      sha256 "17bb23485889862cf2a90f00e22f7db02c75de18d0ac3b26efc86a7e247b6e0d"
      define_method(:install) do
        bin.install "tai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/batuhan0sanli/tai/releases/download/v0.1.0/tai_Linux_arm64.tar.gz"
      sha256 "6508604546460b8fdf7cfca87a6f3d8bfe77c7dd9e92e76a3b4462a34f596b4c"
      define_method(:install) do
        bin.install "tai"
      end
    end
  end

  test do
    system "#{bin}/tai --version"
  end
end
